language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.0'

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
    - composer update --no-interaction --prefer-dist $PREFER_LOWEST

script:
    - phpunit
    - vendor/bin/behat
